### ISSUE TITLE
Deleting isort and the lines in the settings.json

### ISSUE THREAD

**Issue by JosePizarro3** [FAIRmat-NFDI/cookiecutter-nomad-plugin#24]
I would like to delete the linting `"I"` option, together with the options added in the .vscode/settings.json to format the order on save.

It just bugged out a lot during reworking my plugin, but in general, I doubt sorting imports is just interesting if there is the minimal chance that the linting gets crazy.

@blueraft

**Comment by blueraft** [comment]
Thanks for raising the issue.

Internally within Area D import sorting is something we eventually want to bring to nomad-lab, which is why we have gone with import sorting for new plugins. It's also part of the new GUI lints.

Feel free to add or remove any linting rules for your plugins if you wish though.

Can you say a bit more on how the linting gets crazy? From my experience, it would just auto sort the imports on save and thats kind of it.

**Comment by blueraft** [comment]
This was an issue with `isort` extension and `ruff` extension not working well together, the solution is to disable/uninstall `isort` extension since `ruff` provides the same functionality.
